services:
  postgres:
    image: postgres:17
    container_name: ecommerce-postgres
    environment:
      POSTGRES_DB: ecommerce-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
